### ISSUE TITLE
Youtube video cannot be included in playlist

### ISSUE THREAD

**Issue by platisd** [DIT112-V21/group-03#109]
Hi,
Can you please remove the Youtube kids feature from your video? It becomes harder to embed and add to playlist :scream:

**Comment by olgaratu** [comment]
@platisd Hi! I edited the settings. Please try again.

**Comment by platisd** [comment]
Thanks! The "made for kids" term is a bit misleading on YouTube. It's more like "would kids be interested in it" :P
