### ISSUE TITLE
Access favorite functions from home page

### ISSUE THREAD

**Issue by sofie-a** [DIT112-V21/group-03#32]
## User story
 As a user I want to be able to reach the different car modes from the home page

## Acceptance criteria
- The home page of Smart pet buddy app should have a ‘favorites’ section where users can add shortcuts to their favorite functions, for example ‘Race mode’, ‘Manual’, ‘Auto’.
- User can add different pages or functions to their favorites by visiting the page and finding the ‘Favorite’ button
- After adding the page to favorites, it will show up on the home page

**Comment by InaJ123** [comment]
This user story will not be worked on since it does not fit with our current UI. We also agreed that a favorites function would not be very necessary, since our app is not very big and already easy to navigate to the different modes.
