### ISSUE TITLE
Bluetooth Connectivity

### ISSUE THREAD

**Issue by emilieanthony** [DIT112-V21/group-03#33]
As a user, I want to be able to connect my pet to the Smart Pet Buddy

Acceptance criteria: 
- The car should be able to identify a pet by detecting a Bluetooth tag on its collar
- The user can see a notification in the app when the Smart Pet Buddy has detected the Bluetooth tag. User can then choose to connect the Smart Pet Buddy with the pet.

**Comment by InaJ123** [comment]
We have come to the conclusion that we will not be able to implement this user story due to current performance of the smart car emulator. However, if the circumstances would change we will consider re-opening this user story.
